### PR TITLE
Meta API Cleanup

### PR DESCRIPTION
**Pull request by ecorm**
Massive cleanup of meta api, which was scattered everywhere and not updated since it's current stable state in Crossbar.io.

- Broke up meta API feature announcement tags into 'xxx_meta_events' and 'xxx_meta_procedures'. All 'xxx_meta_events' features are to be included in 'roles.broker', whereas all 'xxx_meta_procedures' features are to be included in 'roles.dealer'. The rationale is that meta-events need a Broker to be delivered, whereas meta-procedures need a Dealer to be forwarded and processed. This scheme avoids the need to invent a new role to contain the old 'session_meta_api' tag.
- Created a top-level 'Meta API' section to provide an overview of "standard" meta events.
- Created 'Meta-Event Specifications' and 'Meta-Procedure Specifications' subsections under 'Appendix'. This is intended for lengthy descriptions of all meta events and procedures, including descriptions of arguments.
- Removed 'Sessions / Session Events' section, which is now covered under 'Meta API / Session Meta-Events` section + Appendix.
- Removed 'Sessions / Forced Session Kill' section, and left a note in `Meta API / Session Meta-Procedures`.
- Removed 'Publish and Subscribe / Subscriber Meta Events` and replaced with 'wamp.subscription.on_subscribe_to.<topic>' and 'wamp.subscription.on_unsubscribe_from.<topic>' proposals.
- Removed 'Publish and Subscribe / Subscriber Events` empty section.
- Removed 'Publish and Subscribe / Subscriber Listing` section,  which is now covered under 'Meta API / Session Meta-Procedures` section + Appendix.
- Removed 'Publish and Subscribe / Forced Subscriber Unsubscribe` empty section, and added note in 'Meta API / Session Meta-Procedures`.
- Removed 'Publish and Subscribe / Event History` section, and replaced with similar meta-procedure proposals under 'Meta API / Publication Meta-Procedures'.
- Removed sketchy/incomplete 'Callee Events', 'Callee Listing', 'Forced Callee Unregister', and 'Call History' subsctions, as those would now belong to 'Registration Meta-Events' and 'Registration Meta-Procedures'.
- 'Reflection' section was moved to 'Reflection Meta-Procedures' under the 'Meta API' section.
- Removed 'Predefined Meta Topics'  and 'Predefined Meta Procedures' from 'Appendix / Predefined URIs', as those are now summarized under the 'Meta API' section.
- The table of contents will be updated in a later commit.

### CODE REVIEW

**Comment by ecorm** [comment]
Visit https://github.com/ecorm/WAMP/blob/ecorm-issue-157/spec/advanced.md for a fully-rendered view of my proposed changes.

**Comment by ecorm** [comment]
I looks like the spec is being rebuilt from scratch. Geez, I spent 8 hours on that PR, all for naught...

**Comment by ecorm** [comment]
Okay, I think I can still salvage most of the work put into this PR with the new Advanced Spec organization. Still, a head's-up would have been nice.

**Comment by ecorm** [comment]
@oberstet , may I submit new, separate PRs for each of the `session_meta_api`, `registration_meta_api`, and `subscription_meta_api` pages? Or are you planning other major changes to them.

Before submitting new PRs, I'll wait until the meta api advanced feature announcement "debate" is settled.

**Comment by oberstet** [comment]
> may I submit new, separate PRs for each of the session_meta_api, registration_meta_api, and subscription_meta_api pages? Or are you planning other major changes to them.

@ecorm sorry for disruption again. the major refactoring has happened now: each AP feature in separate page. if you resubmit the work you already did, now targeting the meta API pages, I merge. For now, would be good to try to stay close to CB - not because that's "how things should be", but because we have a concrete proposal to discuss/modify/extend.

**Comment by ecorm** [comment]
> For now, would be good to try to stay close to CB - not because that's "how things should be", but because we have a concrete proposal to discuss/modify/extend.

I agree completely. I'll proceed with how things are done now on CB.

**Comment by ecorm** [comment]
Thanks!

**Pull request closed without merging**
